# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62039b1aa403cf39cfa80a80b8efb72708792837f4819803cad1ef127edaf7c549874bd78adbc253ab3a330ffa407196411ef9231b0dd19f5b4ab0191c48ccce

test:
  secret_key_base: d0417d11a73d9469a4d139dee7dcaadd06ed9010b5c751dc08e075e3db90495bb56a8b530c3c1f3b6b2539fde5c9384ad8ea93be1ddc2c10188400ce4436e84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
